#@ load("@ytt:data", "data")
#@yaml/text-templated-strings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uaa
spec:
  selector:
    matchLabels:
      app: uaa-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: uaa-deployment
    spec: #! pod spec
      containers:
        - name: uaa
          image: "cfidentity/uaa@sha256:(@= data.values.image_sha @)"
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: LOGIN_CONFIG_URL
              value: "classpath:required_configuration.yml"
            - name: spring_profiles
              value: "default,hsqldb"
